defaults:
- repro_singleseq_wce_base.yaml
- repro_feat_extractor_unnormed.yaml
- _self_
generic_model_args:
  chunk_size_grid: 16000
  view_pool: true
  raysampler_args:
    n_rays_per_image_sampled_from_mask: 850
